import type { NodeType, RelType } from './index';
import { NODE_TYPES } from './node-types';
import { REL_TYPES } from './rel-types';

export interface RelConstraint {
  rel: RelType;
  srcTypes: NodeType[];
  dstTypes: NodeType[];
}

export const REL_CONSTRAINTS: RelConstraint[] = [
  {
    rel: REL_TYPES.GRANTS_OBJECT,
    srcTypes: [NODE_TYPES.PROFILE, NODE_TYPES.PERMISSION_SET],
    dstTypes: [NODE_TYPES.OBJECT]
  },
  {
    rel: REL_TYPES.GRANTS_FIELD,
    srcTypes: [NODE_TYPES.PROFILE, NODE_TYPES.PERMISSION_SET],
    dstTypes: [NODE_TYPES.FIELD]
  },
  {
    rel: REL_TYPES.GRANTS_SYSTEM_PERMISSION,
    srcTypes: [NODE_TYPES.PROFILE, NODE_TYPES.PERMISSION_SET],
    dstTypes: [NODE_TYPES.SYSTEM_PERMISSION]
  },
  {
    rel: REL_TYPES.GRANTS_CUSTOM_PERMISSION,
    srcTypes: [NODE_TYPES.PROFILE, NODE_TYPES.PERMISSION_SET],
    dstTypes: [NODE_TYPES.CUSTOM_PERMISSION]
  },
  {
    rel: REL_TYPES.INCLUDES_PERMISSION_SET,
    srcTypes: [NODE_TYPES.PERMISSION_SET_GROUP],
    dstTypes: [NODE_TYPES.PERMISSION_SET]
  },
  {
    rel: REL_TYPES.USES_CONNECTED_APP,
    srcTypes: [NODE_TYPES.PROFILE, NODE_TYPES.PERMISSION_SET],
    dstTypes: [NODE_TYPES.CONNECTED_APP]
  },
  {
    rel: REL_TYPES.HAS_FIELD,
    srcTypes: [NODE_TYPES.OBJECT],
    dstTypes: [NODE_TYPES.FIELD]
  },
  {
    rel: REL_TYPES.TRIGGERS_ON,
    srcTypes: [NODE_TYPES.APEX_TRIGGER, NODE_TYPES.FLOW],
    dstTypes: [NODE_TYPES.OBJECT]
  },
  {
    rel: REL_TYPES.REFERENCES,
    srcTypes: [
      NODE_TYPES.APEX_TRIGGER,
      NODE_TYPES.APEX_CLASS,
      NODE_TYPES.FLOW,
      NODE_TYPES.APEX_PAGE,
      NODE_TYPES.LIGHTNING_COMPONENT_BUNDLE,
      NODE_TYPES.AURA_DEFINITION_BUNDLE,
      NODE_TYPES.QUICK_ACTION,
      NODE_TYPES.LAYOUT
    ],
    dstTypes: [NODE_TYPES.OBJECT, NODE_TYPES.FIELD]
  },
  {
    rel: REL_TYPES.QUERIES,
    srcTypes: [NODE_TYPES.APEX_TRIGGER, NODE_TYPES.APEX_CLASS, NODE_TYPES.FLOW],
    dstTypes: [NODE_TYPES.OBJECT, NODE_TYPES.FIELD]
  },
  {
    rel: REL_TYPES.WRITES,
    srcTypes: [NODE_TYPES.APEX_TRIGGER, NODE_TYPES.APEX_CLASS, NODE_TYPES.FLOW],
    dstTypes: [NODE_TYPES.OBJECT, NODE_TYPES.FIELD]
  }
];
