export const REL_TYPES = {
  GRANTS_OBJECT: 'GRANTS_OBJECT',
  GRANTS_FIELD: 'GRANTS_FIELD',
  GRANTS_SYSTEM_PERMISSION: 'GRANTS_SYSTEM_PERMISSION',
  GRANTS_CUSTOM_PERMISSION: 'GRANTS_CUSTOM_PERMISSION',
  INCLUDES_PERMISSION_SET: 'INCLUDES_PERMISSION_SET',
  USES_CONNECTED_APP: 'USES_CONNECTED_APP',
  HAS_FIELD: 'HAS_FIELD',
  TRIGGERS_ON: 'TRIGGERS_ON',
  REFERENCES: 'REFERENCES',
  QUERIES: 'QUERIES',
  WRITES: 'WRITES'
} as const;

export type RelType = (typeof REL_TYPES)[keyof typeof REL_TYPES];
