FROM node:20-bookworm-slim

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/web/package.json ./apps/web/package.json

RUN pnpm install --frozen-lockfile --prod=false

COPY . .

RUN pnpm --filter web build

EXPOSE 3000

ENV NODE_ENV=production

CMD ["node", "apps/web/.next/standalone/apps/web/server.js"]
